# ========================================================================
# Perform linux and windows builds in parallel and then trigger a release build on success
#
# NOTE: you must have the following variables set in your pipeline as secret variables
# GITHUB_TOKEN
# NUGET_TOKEN
#
# For details, see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#secret-variables
# ========================================================================

# Only trigger CI builds for the master branch, instead of every branch or tags.
# You'll automatically be configured to build PRs, but you can't currently control
# that from the YAML directly
# For details, see https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
  branches:
    include:
      - master
    exclude:
      - tags/*
      - refs/tags/*

# Run the linux and windows jobs in parallel
# For details, see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:
  - template: azure-pipelines_common.yml
    parameters:
      name: linux
      image: ubuntu-16.04

  - template: azure-pipelines_common.yml
    parameters:
      name: windows
      image: vs2017-win2016

  - template: azure-pipelines_common.yml
     parameters:
       name: macOS
       image: xcode9-macos10.13
